### ISSUE TITLE
Why running executable binaries?

### ISSUE THREAD

**Issue by rafaeldelrey** [ViperX7/Alpaca-Turbo#45]
This app, which is supposed to be a Flask app, is trying to run an executable binary named "main".  It has versions for Windows (main.exe) and Linux.  This seems suspect.  Could you elaborate on why such a file is in the zipped distribution?  Why are there no instructions to install it with git?

**Comment by ViperX7** [comment]
You seem to be new to all this but i am using llama.cpp based  binaries to load the models 

Watch your tone no need to be rude

> This app, which is supposed to be a Flask app. 

Who said this 

>  is trying to run an executable binary named "main". It has versions for Windows (main.exe

Yeah i know i made those and there is a m1 arm version too

>  This seems suspect. 

Then don't use or compile yourself 

>  Could you elaborate on why such a file is in the zipped distribution. 

For ease of use otherwise on windows you will endup installing 11 gb of requirements and i will have to solve more problems for people who cant compile

>  Why are there no instructions to install it with git. 

Don't have time to add wanted only one way for users to install send a pr if you can add

Sources for the binaries can be found https;//github.com/viperx7/llama.cpp
